

import Header from "@/presentation/components/Header";
import "../../styles/globals.css";

export const metadata = {
  title: "MFM Ijaiye Region 4 Website",
  description: "A clean and modern church website built with Next.js",
};

export default function PublicLayout({ children }: { children: React.ReactNode }) {
  return (
   <div className="app border border-amber-300 ">
        <Header />
        {children}
   </div>
  );
}











// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
